#!/usr/bin/env node
var testotron = require('./testotron.js');

process.argv.slice(2).forEach(function(file, index) {
  testotron(file);
});


process.on('SIGINT', function () {
  console.log('Exiting');
  process.exit(0);
});